version: '3.8'

services:
  fastapi:
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - ./app/.env
    depends_on:
      - wait_for_db
    command: ["sh", "-c", "python app/wait_for_db.py && uvicorn app.main:app --host 0.0.0.0 --port 8000"]

  wait_for_db:
    image: python:3.10
    volumes:
      - ./app:/app
    working_dir: /app
    command: ["sh", "-c", "pip install psycopg2-binary && python wait_for_db.py"]
    env_file:
      - ./app/.env
